---
title: "Get sequences from Pelechano 2013 annotated transcripts etc."
author: "Edward Wallace, Edward.Wallace@ed.ac.uk"
date: "24 March 2020"
output: 
    html_document:
        toc: true
---

A script to get sequences of transcripts, UTRs, etc, mentioned in `annotateUTRs.Rmd`

# Try with bedtools; works on seqs but not on names

```{bash bedtools_txfasta, eval=FALSE}
bedtools getfasta -s -fullHeader \
-fi ../data/saccharomyces_cerevisiae_R64-2-1_20150113_chrnames.fsa \
-bed ../data/longest_full-ORF_transcripts_ypd.gff3 \
-fo ../out/longest_full-ORF_transcripts_keepintrons_ypd_getfasta.fasta
```

# Try with bioconductor

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Biostrings)
library(rtracklayer)
# library(Rsamtools)
library(tidyverse)
library(here)
```

```{r concat_seqf_function}
concat_seqdf_startorder <- function(seqdf) {
    ID = unique(seqdf$ID)
    Strand = unique(seqdf$strand)
    if( Strand == "+") {
       seqdfarr <- 
           dplyr::arrange(seqdf,start) 
    } else if ( Strand == "-" ) {
        seqdfarr <- 
            dplyr::arrange(seqdf,desc(start))
    }
    tibble::tibble(Seq=paste0(seqdfarr$Seq,collapse = ""))
}
```


## Load genome fasta

```{r load_genome}

Scer_fastafile <- 
    here::here("data","saccharomyces_cerevisiae_R64-2-1_20150113_chrnames.fsa")

Scer_FaFile <- Rsamtools::FaFile(Scer_fastafile)
Scer_fasta <- 
    Biostrings::readDNAStringSet(Scer_fastafile)
```

## Get transcript sequences

```{r longest_tx_seqs,dependson="load_genome"}
granges_ltxs <- 
    here::here("data","longest_full-ORF_transcripts_ypd.gff3") %>%
    rtracklayer::readGFFAsGRanges() 

seqs_ltxs <- Biostrings::getSeq(Scer_FaFile,granges_ltxs) %>%
    magrittr::set_names(granges_ltxs$ID)

Biostrings::writeXStringSet(
    seqs_ltxs, 
    here::here("out",
               "longest_full-ORF_transcripts_keepintrons_ypd.fasta")
)
```

```{r longest_etc_tx_seqs,dependson="load_genome"}
granges_lsplicedtxs <- 
    here::here("out","longest_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons.gff") %>%
    rtracklayer::readGFFAsGRanges() 

seqs_ltxexons <- Biostrings::getSeq(Scer_FaFile,granges_lsplicedtxs) # %>%
    # set_names(paste(granges_splicedtxs$ID,
    #                 chrom(granges_splicedtxs),
    #                 start(granges_splicedtxs),
    #                 sep="_")
    # )

df_lsplicedtxs <- granges_lsplicedtxs %>%
    as.data.frame() %>% 
    tibble::as_tibble() %>%
    dplyr::mutate(Seq = as.character(seqs_ltxexons))

# debug(concat_seqdf_startorder)
# df_splicedtx %>% dplyr::filter(ID=="YAL001C_tx0") %>% concat_seqdf_startorder
# df_splicedtx %>% dplyr::filter(ID=="YAL038W_id004") %>% concat_seqdf_startorder
# df_splicedtx %>% dplyr::filter(ID=="YIL123W_id002") %>% concat_seqdf_startorder

df_lsplicedtxs_seq <- 
    df_lsplicedtxs %>%
    dplyr::group_by(ID) %>%
    dplyr::do(concat_seqdf_startorder(.))

seqs_lsplicedtxs <- 
    df_lsplicedtxs_seq$Seq %>% 
    DNAStringSet() %>%
    magrittr::set_names(df_lsplicedtxs_seq$ID)

Biostrings::writeXStringSet(
    seqs_lsplicedtxs, 
    here::here("out",
               "longest_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons.fasta")
)
```

```{r abundant_etc_tx_seqs,dependson="load_genome"}
granges_asplicedtxs <- 
    here::here("out","abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons.gff") %>%
    rtracklayer::readGFFAsGRanges() 

seqs_atxexons <- Biostrings::getSeq(Scer_FaFile,granges_asplicedtxs) # %>%
    # set_names(paste(granges_splicedtxs$ID,
    #                 chrom(granges_splicedtxs),
    #                 start(granges_splicedtxs),
    #                 sep="_")
    # )

df_asplicedtxs <- granges_asplicedtxs %>%
    as.data.frame() %>% 
    tibble::as_tibble() %>%
    dplyr::mutate(Seq = as.character(seqs_atxexons))

# debug(concat_seqdf_startorder)
# df_splicedtx %>% dplyr::filter(ID=="YAL001C_tx0") %>% concat_seqdf_startorder
# df_splicedtx %>% dplyr::filter(ID=="YAL038W_id004") %>% concat_seqdf_startorder
# df_splicedtx %>% dplyr::filter(ID=="YIL123W_id002") %>% concat_seqdf_startorder

df_asplicedtxs_seq <- 
    df_asplicedtxs %>%
    dplyr::group_by(ID) %>%
    dplyr::do(concat_seqdf_startorder(.))

seqs_asplicedtxs <- 
    df_asplicedtxs_seq$Seq %>% 
    DNAStringSet() %>%
    magrittr::set_names(df_asplicedtxs_seq$ID)

Biostrings::writeXStringSet(
    seqs_asplicedtxs, 
    here::here("out",
               "abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons.fasta")
)
```


## Make subsets containing only verified ORFs

```{r filter_verifiedORFs, dependson=c("longest_etc_tx_seqs","abundant_etc_tx_seqs")}
verifiedORFs <- 
    here::here("data","saccharomyces_cerevisiae_R64-2-1_20150113.gff") %>%
    read_tsv(comment="#",col_names=FALSE) %>%
    filter(X3=="CDS", str_detect(X9,"Verified")) %>%
    pull(X9) %>%
    str_extract("[\\w-]+_CDS") %>%
    unique() %>%
    str_remove("_CDS")

df_verORF_lsplicedtxs_seq <- 
    df_lsplicedtxs_seq %>% 
    mutate(ORF=str_extract(ID,"Y[A-Z0-9-]+")) %>%
    filter(ORF %in% verifiedORFs)

seqs_verORF_lsplicedtxs <- 
    df_verORF_lsplicedtxs_seq$Seq %>% 
    DNAStringSet() %>%
    magrittr::set_names(df_verORF_lsplicedtxs_seq$ID)

Biostrings::writeXStringSet(
    seqs_verORF_lsplicedtxs, 
    here::here("out",
               "verifiedORF_longest_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons.fasta")
)

df_verORF_asplicedtxs_seq <- 
    df_asplicedtxs_seq %>% 
    mutate(ORF=str_extract(ID,"Y[A-Z0-9-]+")) %>%
    filter(ORF %in% verifiedORFs)

seqs_verORF_asplicedtxs <- 
    df_verORF_asplicedtxs_seq$Seq %>% 
    DNAStringSet() %>%
    magrittr::set_names(df_verORF_asplicedtxs_seq$ID)

Biostrings::writeXStringSet(
    seqs_verORF_asplicedtxs, 
    here::here("out",
               "verifiedORF_abundant_full-ORF_ypd_plus_other_fixed_UTR_length_transcripts_nointrons.fasta")
)

```

## Get 5'UTR sequences

```{r longest_5UTRs_keepintrons,dependson="load_genome"}
granges_5UTRs_keep <- 
    here::here("out","longest_five_prime_UTRs_keepintrons.gff") %>%
    rtracklayer::readGFFAsGRanges() 

seqs_5UTRs_keep <- Biostrings::getSeq(Scer_FaFile,granges_5UTRs_keep) %>%
    magrittr::set_names(granges_5UTRs_keep$ID)

Biostrings::writeXStringSet(
    seqs_5UTRs_keep, 
    here::here("out",
               "longest_five_prime_UTRs_keepintrons.fasta")
)
```


